[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  version = "1.1.1"
  name = "github.com/gogo/protobuf"

[[override]]
  version = "1.2.0"
  name = "github.com/golang/protobuf"

[[constraint]]
  name = "github.com/solo-io/solo-kit"
  version = "0.4.2"

[[constraint]]
  name = "github.com/solo-io/go-utils"
  version = "0.6.3"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=v1.13.1"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.1"

[[override]]
  name = "k8s.io/helm"
  version = "v2.12.3"
