{{- if .Values.rbac.create }}

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: glooshot-clusterrole
    labels:
        app: glooshot
        glooshot: rbac
rules:
- apiGroups: ["glooshot.solo.io"]
  resources: ["experiments"]
  verbs: ["*"]

{{- end -}}
