{{- if .Values.rbac.create }}

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: glooshot-clusterrole-binding
  labels:
    app: glooshot
    glooshot: rbac
subjects:
- kind: ServiceAccount
  name: glooshot-serviceaccount
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: glooshot-clusterrole
  apiGroup: rbac.authorization.k8s.io

{{- end -}}
