{{- if .Values.crds.create }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: experiments.glooshot.solo.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: glooshot
spec:
  group: glooshot.solo.io
  names:
    kind: Experiment
    listKind: ExperimentList
    plural: experiments
    shortNames:
      - exp
  scope: Namespaced
  version: v1
{{- end}}
