{{- if .Values.rbac.create }}

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: glooshot-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app: glooshot
    glooshot: rbac
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: glooshot-role
  apiGroup: rbac.authorization.k8s.io

{{- end -}}
