{{- if .Values.rbac.create }}

kind: ServiceAccount
apiVersion: v1
metadata:
  name: glooshot-serviceaccount
  namespace: {{ .Release.Namespace }}
  labels:
    app: glooshot
    glooshot: rbac

{{- end -}}
